### PR TITLE
Add support for macOS

### PR DESCRIPTION
**Pull request by mattprowse**

### CODE REVIEW

**Comment by jvisenti** [comment]
Hey @mattprowse this is awesome! I just have one request before merge:

Because the typealiases that make this work on both iOS and OS X are `public`, they are available everywhere in the app. This can be a bit confusing because of things like `String` vs `NSString` and `URL` vs `NSURL` which are actually entirely different classes. Additionally, the first view view controller is a Swift project is named `ViewController` be default, which leads to a confusing name conflict:

screen shot 2017-02-17 at 9 54 18 am

I think the solution is to namespace the typealiases. Something like this:
```
#if os(macOS)
    import Cocoa

    public enum Anchorage {
        public typealias View = NSView
        public typealias ViewController = NSViewController
        public typealias LayoutPriority = NSLayoutPriority
        public typealias LayoutGuide = NSLayoutGuide

        public static let LayoutPriorityRequired = NSLayoutPriorityRequired
    }
#else
    import UIKit

    public enum Anchorage {
        public typealias View = UIView
        public typealias ViewController = UIViewController
        public typealias LayoutPriority = UILayoutPriority
        public typealias LayoutGuide = UILayoutGuide

        public static let LayoutPriorityRequired = UILayoutPriorityRequired
    }
#endif
```

**Comment by mattprowse** [comment]
Changes made as requested!

**Comment by jvisenti** [comment]
@mattprowse  Thanks! Merged into `develop`. I will put a release out later today.

**Comment by mattprowse** [comment]
Fantastic! Thanks for Anchorage by the way. I've been using nibs and storyboards in my apps since forever. I'm now experimenting with doing it in code and Anchorage makes working with constraints in code so much more pleasant.

**Pull request merged**
