### PR TITLE
Swift 3.0 Compatibility

### PR DESCRIPTION
**Pull request by robcadwallader**

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
@robcadwallader I updated this for Swift 3 in Xcode 8b6, and changed the PR to point to `develop` instead of `master` (GitHub just added that feature today).

**Comment by ZevEisenberg** [comment]
@robcadwallader ah, it looks like the definition of the `~` is going to need a little massaging, but I don't know how to use the new precedence groups.

**Comment by DavdRoman** [comment]
Is there an ETA for Swift 3 compatibility?

**Comment by KingOfBrian** [comment]
Hey @DavdRoman -- it's my high priority list, I'm hoping we'll get some commits up by Monday.  Sorry for the delay!

**Comment by ZevEisenberg** [comment]
In the meantime, you can point your project at the top commit of the Swift 3 branch, and that should work. I say top commit, and not the branch itself, because if the branch is merged and deleted, your reference may break (depending on what dependency manager you're using).

**Pull request merged**
